"""initial

Revision ID: 5535c0b62d3e
Revises: 
Create Date: 2026-05-19 22:11:41.475409

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5535c0b62d3e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_allowed_for_ru_onboarding', sa.Boolean(), nullable=False, comment='Разрешена ли эта страна прав для коммерческой работы в РФ'),
    sa.Column('phone_code', sa.String(length=5), nullable=False),
    sa.Column('license_regex', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_countries_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_countries_iso_code'), ['iso_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_countries_phone_code'), ['phone_code'], unique=False)

    op.create_table('city_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('city_regions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_city_regions_country_id'), ['country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_city_regions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_city_regions_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), server_default='false', nullable=False, comment='Подтвержден ли email'),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Доступ к приложению'),
    sa.Column('is_available', sa.Boolean(), nullable=False, comment='Доступность для заказов'),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False, comment='Главный администратор'),
    sa.Column('role', sa.String(length=20), server_default='customer', nullable=False, comment='Роль пользователя'),
    sa.Column('is_banned', sa.Boolean(), server_default='false', nullable=False, comment='Заблокирован ли'),
    sa.Column('last_active', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_country_id'), ['country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_active'), ['last_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_uuid'), ['uuid'], unique=True)

    op.create_table('admin_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_logs_target_id'), ['target_id'], unique=False)

    op.create_table('location_hubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['city_regions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_hubs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_hubs_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_hubs_region_id'), ['region_id'], unique=False)

    op.create_table('onboarding_applications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('target_region_id', sa.Integer(), nullable=False),
    sa.Column('target_role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending_legal', nullable=False),
    sa.Column('bank_type', sa.String(length=20), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('admin_comment', sa.String(length=255), nullable=True),
    sa.Column('survey_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_region_id'], ['city_regions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('onboarding_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_applications_id'), ['id'], unique=False)
        batch_op.create_index('ix_onboarding_applications_status_created_at', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_onboarding_applications_target_region_id'), ['target_region_id'], unique=False)

    op.create_table('supplier_profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=True, comment='Языки общения водителя'),
    sa.Column('base_region_id', sa.Integer(), nullable=False),
    sa.Column('car_class', sa.String(length=20), nullable=False),
    sa.Column('car_brand', sa.String(length=50), nullable=False),
    sa.Column('car_model', sa.String(length=100), nullable=False),
    sa.Column('car_year', sa.BigInteger(), nullable=False),
    sa.Column('car_number', sa.String(length=20), nullable=False),
    sa.Column('car_color', sa.String(length=30), nullable=False),
    sa.Column('vin_number', sa.String(length=17), nullable=True),
    sa.Column('license_number', sa.String(length=20), nullable=False),
    sa.Column('license_expiry_date', sa.Date(), nullable=False),
    sa.Column('experience_years', sa.BigInteger(), nullable=False),
    sa.Column('photo_selfie', sa.String(length=500), nullable=False),
    sa.Column('photo_car_side', sa.String(length=500), nullable=False),
    sa.Column('photo_car_interior', sa.String(length=500), nullable=False),
    sa.Column('photo_car_front', sa.String(length=500), nullable=False),
    sa.Column('photo_car_back', sa.String(length=500), nullable=False),
    sa.Column('photo_sts_front', sa.String(length=500), nullable=False),
    sa.Column('photo_sts_back', sa.String(length=500), nullable=False),
    sa.Column('photo_license', sa.String(length=500), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_region_id'], ['city_regions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('supplier_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_profiles_base_region_id'), ['base_region_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_profiles_car_brand'), ['car_brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_profiles_car_class'), ['car_class'], unique=False)

    op.create_table('trip_guide_profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('base_region_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('photo_certificate', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['base_region_id'], ['city_regions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('trip_guide_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_guide_profiles_base_region_id'), ['base_region_id'], unique=False)

    op.create_table('transfer_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=False),
    sa.Column('to_location_id', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('estimated_time_min', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['location_hubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_location_id'], ['location_hubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer_routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_routes_from_location_id'), ['from_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfer_routes_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfer_routes_to_location_id'), ['to_location_id'], unique=False)

    op.create_table('route_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('car_class', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['transfer_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_prices_car_class'), ['car_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_prices_route_id'), ['route_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_prices_route_id'))
        batch_op.drop_index(batch_op.f('ix_route_prices_car_class'))

    op.drop_table('route_prices')
    with op.batch_alter_table('transfer_routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_routes_to_location_id'))
        batch_op.drop_index(batch_op.f('ix_transfer_routes_is_active'))
        batch_op.drop_index(batch_op.f('ix_transfer_routes_from_location_id'))

    op.drop_table('transfer_routes')
    with op.batch_alter_table('trip_guide_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_guide_profiles_base_region_id'))

    op.drop_table('trip_guide_profiles')
    with op.batch_alter_table('supplier_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_profiles_car_class'))
        batch_op.drop_index(batch_op.f('ix_supplier_profiles_car_brand'))
        batch_op.drop_index(batch_op.f('ix_supplier_profiles_base_region_id'))

    op.drop_table('supplier_profiles')
    with op.batch_alter_table('onboarding_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onboarding_applications_target_region_id'))
        batch_op.drop_index('ix_onboarding_applications_status_created_at')
        batch_op.drop_index(batch_op.f('ix_onboarding_applications_id'))

    op.drop_table('onboarding_applications')
    with op.batch_alter_table('location_hubs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_hubs_region_id'))
        batch_op.drop_index(batch_op.f('ix_location_hubs_name'))

    op.drop_table('location_hubs')
    with op.batch_alter_table('admin_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_logs_target_id'))
        batch_op.drop_index(batch_op.f('ix_admin_logs_id'))
        batch_op.drop_index(batch_op.f('ix_admin_logs_action'))

    op.drop_table('admin_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_uuid'))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_last_active'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_first_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_users_country_id'))

    op.drop_table('users')
    with op.batch_alter_table('city_regions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_city_regions_name'))
        batch_op.drop_index(batch_op.f('ix_city_regions_is_active'))
        batch_op.drop_index(batch_op.f('ix_city_regions_country_id'))

    op.drop_table('city_regions')
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_countries_phone_code'))
        batch_op.drop_index(batch_op.f('ix_countries_iso_code'))
        batch_op.drop_index(batch_op.f('ix_countries_is_active'))

    op.drop_table('countries')
    # ### end Alembic commands ###
