"""initial

Revision ID: 620ca10d4739
Revises:
Create Date: 2026-05-13 15:02:19.352478

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "620ca10d4739"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("uuid", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column(
            "is_email_verified", sa.Boolean(), server_default="false", nullable=False, comment="Подтвержден ли email"
        ),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("photo_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False, comment="Доступ к приложению"),
        sa.Column("is_available", sa.Boolean(), nullable=False, comment="Доступность для заказов"),
        sa.Column(
            "is_superuser", sa.Boolean(), server_default="false", nullable=False, comment="Главный администратор"
        ),
        sa.Column("role", sa.String(length=20), server_default="customer", nullable=False, comment="Роль пользователя"),
        sa.Column("is_banned", sa.Boolean(), server_default="false", nullable=False, comment="Заблокирован ли"),
        sa.Column("last_active", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("app_version", sa.String(length=50), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_first_name"), ["first_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_last_active"), ["last_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_phone"), ["phone"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_role"), ["role"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_uuid"), ["uuid"], unique=True)

    op.create_table(
        "admin_logs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("admin_id", sa.BigInteger(), nullable=False),
        sa.Column("target_id", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["admin_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("admin_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_admin_logs_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_admin_logs_id"), ["id"], unique=False)

    op.create_table(
        "onboarding_applications",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("target_role", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending_legal", nullable=False),
        sa.Column("bank_type", sa.String(length=20), nullable=True),
        sa.Column("external_id", sa.String(length=100), nullable=True),
        sa.Column("inn", sa.String(length=12), nullable=True),
        sa.Column("admin_comment", sa.String(length=255), nullable=True),
        sa.Column("survey_payload", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    with op.batch_alter_table("onboarding_applications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_onboarding_applications_id"), ["id"], unique=False)

    op.create_table(
        "supplier_profiles",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("car_brand", sa.String(length=50), nullable=False),
        sa.Column("car_model", sa.String(length=100), nullable=False),
        sa.Column("car_year", sa.BigInteger(), nullable=False),
        sa.Column("car_number", sa.String(length=20), nullable=False),
        sa.Column("car_color", sa.String(length=30), nullable=False),
        sa.Column("vin_number", sa.String(length=17), nullable=True),
        sa.Column("license_number", sa.String(length=20), nullable=False),
        sa.Column("license_expiry_date", sa.Date(), nullable=False),
        sa.Column("experience_years", sa.BigInteger(), nullable=False),
        sa.Column("license_country", sa.String(length=50), nullable=False),
        sa.Column("photo_selfie", sa.String(length=500), nullable=False),
        sa.Column("photo_car_side", sa.String(length=500), nullable=False),
        sa.Column("photo_car_interior", sa.String(length=500), nullable=False),
        sa.Column("photo_car_front", sa.String(length=500), nullable=False),
        sa.Column("photo_car_back", sa.String(length=500), nullable=False),
        sa.Column("photo_sts_front", sa.String(length=500), nullable=False),
        sa.Column("photo_sts_back", sa.String(length=500), nullable=False),
        sa.Column("photo_license", sa.String(length=500), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    with op.batch_alter_table("supplier_profiles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_supplier_profiles_car_brand"), ["car_brand"], unique=False)

    op.create_table(
        "trip_guide_profiles",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("bio", sa.String(length=1000), nullable=True),
        sa.Column("languages", sa.JSON(), nullable=True),
        sa.Column("specialization", sa.String(length=255), nullable=True),
        sa.Column("photo_certificate", sa.String(length=500), nullable=True),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trip_guide_profiles")
    with op.batch_alter_table("supplier_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_supplier_profiles_car_brand"))

    op.drop_table("supplier_profiles")
    with op.batch_alter_table("onboarding_applications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_onboarding_applications_id"))

    op.drop_table("onboarding_applications")
    with op.batch_alter_table("admin_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admin_logs_id"))
        batch_op.drop_index(batch_op.f("ix_admin_logs_action"))

    op.drop_table("admin_logs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_uuid"))
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_role"))
        batch_op.drop_index(batch_op.f("ix_users_phone"))
        batch_op.drop_index(batch_op.f("ix_users_last_active"))
        batch_op.drop_index(batch_op.f("ix_users_id"))
        batch_op.drop_index(batch_op.f("ix_users_first_name"))
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.drop_index(batch_op.f("ix_users_deleted_at"))

    op.drop_table("users")
    # ### end Alembic commands ###
