[project]
name = "new-app-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aioboto3>=15.5.0",
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "bcrypt==4.0.1",
    "celery>=5.6.3",
    "email-validator>=2.3.0",
    "fastapi[standard]>=0.135.3",
    "httpx[http2]>=0.28.1",
    "packaging>=26.0",
    "passlib>=1.7.4",
    "pydantic-extra-types>=2.11.2",
    "pydantic-settings>=2.13.1",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.26",
    "python-slugify>=8.0.4",
    "redis>=7.4.0",
    "sqlalchemy>=2.0.49",
    "user-agents>=2.2.0",
    "uvicorn>=0.44.0",
]

[dependency-groups]
dev = [
    "faker>=40.13.0",
    "httpx>=0.28.1",
    "pytest>=9.0.3",
    "pytest-asyncio>=1.3.0",
    "ruff>=0.15.10",
]


# настройки Ruff для удаления неиспользуемых импортов
[tool.ruff]
# Общие настройки
# Ограничение длины строки (золотой стандарт Python)
line-length = 88

[tool.ruff.lint]
# Группируем ВСЕ настройки линтера в одной секции
select = ["E", "F", "I", "N", "B", "UP"]
fixable = ["ALL"]

[tool.ruff.format]
# Настройки форматирования
quote-style = "double"
indent-style = "space"
